# FILE: cloudbuild.yaml

steps:
# --- BUILD STEPS ---

# 1. Build the API container image
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build API'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/775014090096/dataloggerapi:latest'
    - '--file=ingestion-api/Dockerfile' # Correctly points to the API Dockerfile
    - '.'

# 2. Build the Worker container image
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build Worker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/775014090096/dataloggerworker:latest'
    - '--file=database-worker/Dockerfile' # Correctly points to the Worker Dockerfile
    - '.'

# --- PUSH STEPS ---

# 3. Push the API image to the registry
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push API'
  args: ['push', 'gcr.io/775014090096/dataloggerapi:latest']

# 4. Push the Worker image to the registry
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push Worker'
  args: ['push', 'gcr.io/775014090096/dataloggerworker:latest']

# --- DEPLOY STEPS ---

# 5. Deploy the API Service to Cloud Run (Public)
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'Deploy API'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'dataloggerapi'
    - '--image'
    - 'gcr.io/775014090096/dataloggerapi:latest'
    - '--region'
    - 'europe-west1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--set-env-vars'
    - 'REDIS_URL=redis://default:spKR06XpWueVQCms3ai7oNXlC1SQlAj1@redis-18367.c114.us-east-1-4.ec2.redns.redis-cloud.com:18367'

# 6. Deploy the Worker Service to Cloud Run (Private)
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'Deploy Worker'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'dataloggerworker'
    - '--image'
    - 'gcr.io/775014090096/dataloggerworker:latest'
    - '--region'
    - 'europe-west1'
    - '--platform'
    - 'managed'
    - '--no-allow-unauthenticated'
    - '--set-env-vars'
    - 'REDIS_URL=redis://default:spKR06XpWueVQCms3ai7oNXlC1SQlAj1@redis-18367.c114.us-east-1-4.ec2.redns.redis-cloud.com:18367'

# List all the images that were built
images:
- 'gcr.io/775014090096/dataloggerapi:latest'
- 'gcr.io/775014090096/dataloggerworker:latest'
